services:
  web:
    build: .
    ports:
      - "3001:3000"
    volumes:
      - .:/rails
    environment:
      RAILS_ENV: development
    command: sh -c "rm -f tmp/pids/server.pid && ./bin/rails server -b 0.0.0.0"
